'use client';
import Image from 'next/image';import {useEffect,useState} from 'react';import {motion} from 'framer-motion';import Lenis from '@studio-freight/lenis';
const projects=[
['Deep Research Agent','Autonomous Multi-Agent Research System','AI Engineer, Multi-Agent Systems','2026','Solo','Python · LangGraph · LangChain · Google Gemini · Tavily API','LangGraph multi-agent research system with scoping, supervision, parallel researchers and citation-backed report synthesis.','https://github.com/Balavishvas/DeepResearchAgent','/images/projects/deep-research.jpg'],
['AdvocAI','RAG-Based Legal Document Q&A','Full-Stack AI Developer','2025','Solo','Python · FastAPI · LangChain · LangGraph · FAISS · HuggingFace · Groq · React · Redis','Contract PDF Q&A with grounded page citations, session-isolated FAISS retrieval and Redis semantic caching.','https://github.com/Balavishvas/AdvocAI-RAG','/images/projects/advocai.jpg'],
['GitHub Profile Inspector','Developer Analytics Tool','Full-Stack Developer','2026','Solo','Python · JavaScript · HTML · CSS · GitHub REST API','CLI and web analytics for stars, repositories, followers and language distribution with filtering and rate-limit handling.','https://github.com/Balavishvas/github-profile-inspector','/images/projects/github-inspector.jpg'],
['TourChain','Tourist Safety Monitoring & Incident Response','AI & Backend Developer','2025','Solo','Python · JavaScript · HTML · CSS · GPS APIs · Anomaly Detection','Real-time tourist GPS monitoring and anomaly detection platform for emergency response and law-enforcement dashboards.','https://github.com/Balavishvas/Touriest-Safety-Monitoring-And-Incident-Response-System','/images/projects/tourchain.jpg']];
const tech=['Python','Java','LangChain','LangGraph','FastAPI','React','Redis','FAISS','HuggingFace','Groq','Google Gemini','GitHub','HTML','CSS','JavaScript','Pandas','NumPy','Scikit-learn','SQL','Git','Vercel','Tavily','Transformers','Pydantic'];
export default function Page(){useEffect(()=>{const l=new Lenis({duration:1.1});let f=(t:number)=>{l.raf(t);requestAnimationFrame(f)};requestAnimationFrame(f);return()=>l.destroy()},[]);
return <main><Header/><Intro/>
<section id="home" className="hero"><div className="hero-photo"><Image src="/images/hero-portrait.jpg" alt="Balavishvas" fill priority/></div><h1><span>Bala</span><span>vishvas</span></h1><div className="hero-bottom"><p>AI systems, agents & the code in between. I take the build seriously.</p><div>{['Generative AI','RAG Systems','Multi-Agent Workflows','Backend APIs','Full-Stack Apps'].map(x=><i key={x}>{x}</i>)}</div></div></section>
<section className="about"><div className="about-img"><Image src="/images/about-float.jpg" alt="" fill/></div><p>Hi, I'm Bala, a final-year B.Tech AI & Data Science student who builds LLM-powered products from idea to deployment. RAG pipelines, multi-agent workflows, FastAPI backends and the React interfaces they run on, all shipped, not just prototyped.</p></section>
<section className="tech"><small>(TECH I BUILD WITH)</small><div className="ticker">{tech.concat(tech).map((x,i)=><b key={i}>{x}</b>)}</div></section>
<section id="work" className="work"><h2>Selected<br/>Projects</h2>{projects.map((p,i)=><a className="project" key={p[0]} href={p[7]} target="_blank"><div className="project-head"><small>Jump To Project ↗</small><small>{p[5]}</small></div><div className="project-grid"><div className="project-img"><Image src={p[8]} alt={p[0]} fill/></div><div><h3>{p[0]}</h3><em>{p[1]}</em><p>{p[6]}</p><div className="meta"><span>ROLE<br/><strong>{p[2]}</strong></span><span>YEAR<br/><strong>{p[3]}</strong></span><span>TEAM<br/><strong>{p[4]}</strong></span></div></div></div></a>)}</section>
<section id="lab" className="lab"><div><Image src="/images/lab-image.jpg" alt="The Lab" fill/></div><article><small>The Lab</small><h2>The<br/>Lab</h2><p>A messy, honest dump of my experiments: half-finished agents, retrieval tweaks, prompt tests and weekend builds. Care to take a peek inside?</p><a href="https://github.com/Balavishvas">Enter The Lab ↗</a><a href="/Balavishvas_AI_Resume.pdf" download="Balavishvas_M_Resume.pdf">Resume ↓</a></article></section>
<section className="skills"><small>Skillset</small>{[['01','Generative AI','LLM apps, prompt engineering, structured outputs and evaluation.'],['02','RAG & Agents','retrieval pipelines, LangChain/LangGraph multi-agent workflows.'],['03','Backend & APIs','FastAPI services, caching, session handling, deployment.'],['04','Full-Stack','React, JavaScript, HTML/CSS interfaces that make AI usable.']].map(x=><div key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</section>
<section className="quote"><video src="/videos/bg.mp4" autoPlay muted loop playsInline/><div>Consistency, persistence, and building things that actually work.</div></section>
<Contact/><footer><h2>BALAVISHVAS®</h2><div><p>Somewhere between models and production.</p><nav><a href="mailto:balavishvas2005@gmail.com">Email</a><a href="https://github.com/Balavishvas">GitHub</a><a href="https://linkedin.com/in/balavishvas-m-bb2240377">LinkedIn</a><a href="/Balavishvas_AI_Resume.pdf" download="Balavishvas_M_Resume.pdf">Resume</a></nav><small>© 2026 Balavishvas M. All rights reserved.</small></div></footer></main>}
function Intro(){const [x,setX]=useState(true);useEffect(()=>{let t=setTimeout(()=>setX(false),1700);return()=>clearTimeout(t)},[]);return x?<div className="intro"><b>BALA</b><div className="intro-stack">{[1,2,3,4,5,6,7,8,9].map(i=><Image key={i} src={'/images/intro/intro-'+i+'.jpg'} alt="" fill/>)}</div><b>VISHVAS</b></div>:null}
function Header(){return <header><a href="#home">BALAVISHVAS®</a><nav><a href="#home">Home</a><a href="#work">Work</a><a href="#lab">Lab</a></nav><a href="mailto:balavishvas2005@gmail.com">BALAVISHVAS2005@GMAIL.COM</a><a className="resume" href="/Balavishvas_AI_Resume.pdf" download="Balavishvas_M_Resume.pdf">Download Resume ↓</a></header>}
function Contact(){return <section id="contact" className="contact"><small>(LEAVE YOUR DETAILS)</small><h2>OPEN THE DOOR</h2><form action={'https://formspree.io/f/'+(process.env.NEXT_PUBLIC_FORMSPREE_ID||'YOUR_ID')} method="POST"><input required name="name" placeholder="NAME"/><input required type="email" name="email" placeholder="EMAIL"/><input name="phone" placeholder="PHONE"/><select name="reason" defaultValue=""><option value="" disabled>REASON</option><option>Internship / Job opportunity</option><option>Freelance project</option><option>Just saying hi</option></select><textarea required name="message" placeholder="MESSAGE"/><button>Send Details →</button></form><p>Or just write: <a href="mailto:balavishvas2005@gmail.com">balavishvas2005@gmail.com</a><br/>No spam. A real reply, usually the same day.</p></section>}